version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2021-10-13T00-23-17Z
    command: server /data --address ":9000"
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_BROWSER=off
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
