version: "3.9"

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    network_mode: host
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./data:/data
